apiVersion: apps/v1
kind: Deployment
metadata:
  name: memory-waster
  labels:
    app: memory-waster
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx-nolimits
        image: nginxdemos/hello
        resources:
          limits:
            memory: "512M"
        ports:
        - containerPort: 80
