apiVersion: apps/v1
kind: Deployment
metadata:
  name: memory-waster
  namespace: mem-example
  labels:
    app: memory-waster
spec:
  replicas: 1
  selector:
    matchLabels:
      app: memory-waster
  template:
    metadata:
      labels:
        app: memory-waster
    spec:
      containers:
      - name: memory-demo-ctr
        image: polinux/stress
        resources:
          limits:
            memory: "200Mi"
          requests:
            memory: "100Mi"
        command: ["/bin/sh"] 
        args: ["-c", "sleep 1; stress --vm 1 --vm-bytes 250M --vm-hang 1"]
