apiVersion: apps/v1
kind: Deployment
metadata:
  name: memory-waster
  namespace: mem-example
  labels:
    app: memory-waster
spec:
  replicas: 15
  selector:
    matchLabels:
      app: memory-waster
  template:
    metadata:
      labels:
        app: memory-waster
    spec:
      terminationGracePeriodSeconds: 5
      containers:
      - name: memory-demo-ctr
        image: polinux/stress
        resources:
          limits:
            memory: "200Mi"
          requests:
            memory: "50Mi"
        command: ["/bin/sh"] 
        args: ["-c", "sleep 30; stress --vm 1 --vm-bytes 150M --vm-hang 1"]
